repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pipenv run pylint
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false
