repos:
  - repo: https://github.com/python-poetry/poetry
    rev: ''
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
      - id: poetry-install
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        stages: [commit]
        language: system
        entry: poetry run ruff ./src
        types: [python]
        exclude: src/code_review__web/data/*

      - id: mypy
        name: MYPY
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    exclude: 3rd_party
    hooks:
      - id: check-docstring-first
        name: Check docstring

      - id: check-json
        name: Check json

      - id: check-yaml
        name: Check yaml
        entry: check-yaml --unsafe

      - id: check-added-large-files
        name: Check added large files
