repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        stages: [commit]
        language: system
        entry: pipenv run ruff ./src
        types: [python]
        exclude: setup.py src/code_review__web/code_review_project/epylint/* src/code_review__web/data/*

      - id: flake8
        name: Flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: MYPY
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    exclude: 3rd_party
    hooks:
      - id: check-docstring-first
        name: Check docstring

      - id: check-json
        name: Check json

      - id: check-yaml
        name: Check yaml
        entry: check-yaml --unsafe

      - id: check-added-large-files
        name: Check added large files
