# Generated by Django 4.2.4 on 2023-09-01 18:48

import datetime
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ..models import user_directory_path


class Migration(migrations.Migration):  # type: ignore

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('file_name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('file_data', models.FileField(upload_to=user_directory_path, verbose_name='File')),
                ('is_reviewed', models.CharField(choices=[
                    ('reviewed', 'Reviewed'),
                    ('not_reviewed', 'Not reviewed'),
                    ('in_review', 'In review')
                ], default='not_reviewed', verbose_name='Review state')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-created_at',),
            },
        ),
    ]
