name: linters

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install mypy
    - name: Lint with RUFF
      run: ruff check ./src --ignore D100,D101,D102,D103,D104,D107,D105,D106,D200,D400,D413,E501,E402,N815,N805,EXE002,RUF012,PGH003,A003,ARG002,RET504,RET502,RET505,G004,RUF100 --line-length 180 $(git ls-files '*.py')
    - name: Lint with MYPY
      run: mypy ./src --follow-imports=normal --ignore-missing-imports --strict --exclude 'src/code_review__web/code_review__app/models.py'
